CREATE TABLE [dbo].[RequestViews] (
    [Id]                        INT            IDENTITY (1, 1) NOT NULL,
    [Name]                      NVARCHAR (MAX) NULL,
    [Attachments]               BIT            DEFAULT ((0)) NOT NULL,
    [BIContact]                 BIT            DEFAULT ((0)) NOT NULL,
    [BIGateQuestionaireUrl]     BIT            DEFAULT ((0)) NOT NULL,
    [BIGateStatus]              BIT            DEFAULT ((0)) NOT NULL,
    [BIRequest]                 BIT            DEFAULT ((0)) NOT NULL,
    [BenefitCase]               BIT            DEFAULT ((0)) NOT NULL,
    [COEPriority]               BIT            DEFAULT ((0)) NOT NULL,
    [CRNo]                      BIT            DEFAULT ((0)) NOT NULL,
    [CreatedBy]                 BIT            DEFAULT ((0)) NOT NULL,
    [CreatedOn]                 BIT            DEFAULT ((0)) NOT NULL,
    [DCOEDevelopmentLead]       BIT            DEFAULT ((0)) NOT NULL,
    [DCOEEstimate]              BIT            DEFAULT ((0)) NOT NULL,
    [DevelopmentTeams]          BIT            DEFAULT ((0)) NOT NULL,
    [EBSGateQuestionaireUrl]    BIT            DEFAULT ((0)) NOT NULL,
    [EBSGateStatus]             BIT            DEFAULT ((0)) NOT NULL,
    [EstimateInfra]             BIT            DEFAULT ((0)) NOT NULL,
    [FrontLineContact]          BIT            DEFAULT ((0)) NOT NULL,
    [FunctionalContact]         BIT            DEFAULT ((0)) NOT NULL,
    [GBSPriority]               BIT            DEFAULT ((0)) NOT NULL,
    [ImpactedStreams]           BIT            DEFAULT ((0)) NOT NULL,
    [MD_50]                     BIT            DEFAULT ((0)) NOT NULL,
    [MD_50_DueDate]             BIT            DEFAULT ((0)) NOT NULL,
    [MD_70]                     BIT            DEFAULT ((0)) NOT NULL,
    [MD_70_DueDate]             BIT            DEFAULT ((0)) NOT NULL,
    [ModifiedBy]                BIT            DEFAULT ((0)) NOT NULL,
    [ModifiedOn]                BIT            DEFAULT ((0)) NOT NULL,
    [Modules]                   BIT            DEFAULT ((0)) NOT NULL,
    [NextBIGate]                BIT            DEFAULT ((0)) NOT NULL,
    [NextEBSGate]               BIT            DEFAULT ((0)) NOT NULL,
    [OTMEBSGate]                BIT            DEFAULT ((0)) NOT NULL,
    [Next_NETGate]              BIT            DEFAULT ((0)) NOT NULL,
    [Notes]                     BIT            DEFAULT ((0)) NOT NULL,
    [OTMGateQuestionaireUrl]    BIT            DEFAULT ((0)) NOT NULL,
    [OTMGateStatus]             BIT            DEFAULT ((0)) NOT NULL,
    [OracleDevEstimateOffShore] BIT            DEFAULT ((0)) NOT NULL,
    [OracleDevEstimateOnShore]  BIT            DEFAULT ((0)) NOT NULL,
    [OracleDevelopmentLead]     BIT            DEFAULT ((0)) NOT NULL,
    [OraclePreProdEnvironments] BIT            DEFAULT ((0)) NOT NULL,
    [OrderBy]                   NVARCHAR (MAX) NULL,
    [OriginalSystemReference]   BIT            DEFAULT ((0)) NOT NULL,
    [OwningSite]                BIT            DEFAULT ((0)) NOT NULL,
    [OwningStream]              BIT            DEFAULT ((0)) NOT NULL,
    [Problem]                   BIT            DEFAULT ((0)) NOT NULL,
    [ProductionDate]            BIT            DEFAULT ((0)) NOT NULL,
    [ProjectName]               BIT            DEFAULT ((0)) NOT NULL,
    [ReadyForBIGate]            BIT            DEFAULT ((0)) NOT NULL,
    [ReadyForEBSGate]           BIT            DEFAULT ((0)) NOT NULL,
    [ReadyForOTMGate]           BIT            DEFAULT ((0)) NOT NULL,
    [ReadyFor_NETGate]          BIT            DEFAULT ((0)) NOT NULL,
    [Regions]                   BIT            DEFAULT ((0)) NOT NULL,
    [Attribute9]                BIT            DEFAULT ((0)) NOT NULL,
    [Requestor]                 BIT            DEFAULT ((0)) NOT NULL,
    [SBUs]                      BIT            DEFAULT ((0)) NOT NULL,
    [Status]                    BIT            DEFAULT ((0)) NOT NULL,
    [TIPUrl]                    BIT            DEFAULT ((0)) NOT NULL,
    [TestingDate]               BIT            DEFAULT ((0)) NOT NULL,
    [TotalEstimate]             BIT            DEFAULT ((0)) NOT NULL,
    [WhereClaus]                NVARCHAR (MAX) NULL,
    [_NETGateQuestionaireUrl]   BIT            DEFAULT ((0)) NOT NULL,
    [_NETGateStatus]            BIT            DEFAULT ((0)) NOT NULL,
    [Attribute1]                BIT            DEFAULT ((0)) NOT NULL,
    [Attribute10]               BIT            DEFAULT ((0)) NOT NULL,
    [Attribute2]                BIT            DEFAULT ((0)) NOT NULL,
    [Attribute3]                BIT            DEFAULT ((0)) NOT NULL,
    [Attribute4]                BIT            DEFAULT ((0)) NOT NULL,
    [Attribute5]                BIT            DEFAULT ((0)) NOT NULL,
    [Attribute6]                BIT            DEFAULT ((0)) NOT NULL,
    [Attribute7]                BIT            DEFAULT ((0)) NOT NULL,
    [Attribute8]                BIT            DEFAULT ((0)) NOT NULL,
	Application	bit null
    CONSTRAINT [PK_RequestViews] PRIMARY KEY CLUSTERED ([Id] ASC)
);

