//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADServiceRef
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ADUserAttributeEnum", Namespace="http://schemas.ppg.com/adservice/V1_0")]
    public enum ADUserAttributeEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullName = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FirstName = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastName = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DistinguishedName = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NetworkID = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PPGID = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Location = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Company = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Domain = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChargeNumber = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Telphone = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JobTitle = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Country = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SBU = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManagerPpgId = 15,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
    public partial class ADServiceFault : object
    {
        
        private string ExceptionMessageField;
        
        private string SourceField;
        
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage
        {
            get
            {
                return this.ExceptionMessageField;
            }
            set
            {
                this.ExceptionMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ADUser", Namespace="http://schemas.ppg.com/adservice/V1_0")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ADServiceRef.ADUserExtended))]
    public partial class ADUser : object
    {
        
        private string ChargeNumberField;
        
        private string CompanyField;
        
        private string CountryField;
        
        private string DistinguishedNameField;
        
        private string DomainField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string FullNameField;
        
        private string JobTitleField;
        
        private string LastNameField;
        
        private string LocationField;
        
        private string ManagerPpgIdField;
        
        private string NetworkIdField;
        
        private string PpgIdField;
        
        private string SBUField;
        
        private string TelephoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChargeNumber
        {
            get
            {
                return this.ChargeNumberField;
            }
            set
            {
                this.ChargeNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistinguishedName
        {
            get
            {
                return this.DistinguishedNameField;
            }
            set
            {
                this.DistinguishedNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain
        {
            get
            {
                return this.DomainField;
            }
            set
            {
                this.DomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle
        {
            get
            {
                return this.JobTitleField;
            }
            set
            {
                this.JobTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagerPpgId
        {
            get
            {
                return this.ManagerPpgIdField;
            }
            set
            {
                this.ManagerPpgIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NetworkId
        {
            get
            {
                return this.NetworkIdField;
            }
            set
            {
                this.NetworkIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PpgId
        {
            get
            {
                return this.PpgIdField;
            }
            set
            {
                this.PpgIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SBU
        {
            get
            {
                return this.SBUField;
            }
            set
            {
                this.SBUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone
        {
            get
            {
                return this.TelephoneField;
            }
            set
            {
                this.TelephoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ADUserExtended", Namespace="http://schemas.ppg.com/adservice/V1_0")]
    public partial class ADUserExtended : ADServiceRef.ADUser
    {
        
        private ADServiceRef.ADUser ManagerField;
        
        private string SiteOUField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ADServiceRef.ADUser Manager
        {
            get
            {
                return this.ManagerField;
            }
            set
            {
                this.ManagerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteOU
        {
            get
            {
                return this.SiteOUField;
            }
            set
            {
                this.SiteOUField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ADGroup", Namespace="http://schemas.ppg.com/adservice/V1_0")]
    public partial class ADGroup : object
    {
        
        private string DistinguishedNameField;
        
        private bool DistrubutionListField;
        
        private string EmailField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistinguishedName
        {
            get
            {
                return this.DistinguishedNameField;
            }
            set
            {
                this.DistinguishedNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DistrubutionList
        {
            get
            {
                return this.DistrubutionListField;
            }
            set
            {
                this.DistrubutionListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ppg.com/adservice/V1_0", ConfigurationName="ADServiceRef.ADService")]
    public interface ADService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoTest", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoTestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoTestADServiceFaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ADServiceRef.ADUserAttributeEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ADServiceRef.ADServiceFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ADServiceRef.ADUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ADServiceRef.ADUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ADServiceRef.ADUserExtended[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ADServiceRef.ADUserExtended))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ADServiceRef.ADGroup[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ADServiceRef.ADGroup))]
        System.Threading.Tasks.Task<object> GetUserInfoTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/ADServiceAutoCompleteLastName", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/ADServiceAutoCompleteLastNameResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/ADServiceAutoCompleteLastNameADServic" +
            "eFaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADUser[]> ADServiceAutoCompleteLastNameAsync(string text, string count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/ADServiceAutoCompleteLastNameExtended" +
            "", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/ADServiceAutoCompleteLastNameExtended" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/ADServiceAutoCompleteLastNameExtended" +
            "ADServiceFaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADUserExtended[]> ADServiceAutoCompleteLastNameExtendedAsync(string text, string count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetGroupCount", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetGroupCountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetGroupCountADServiceFaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<int> GetGroupCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserCount", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserCountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserCountADServiceFaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<int> GetUserCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoByPpgId", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoByPpgIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoByPpgIdADServiceFaultFault" +
            "", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADUser[]> GetUserInfoByPpgIdAsync(string ppgId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoExtendedByPpgId", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoExtendedByPpgIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoExtendedByPpgIdADServiceFa" +
            "ultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADUserExtended[]> GetUserInfoExtendedByPpgIdAsync(string ppgId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoByNetworkId", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoByNetworkIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoByNetworkIdADServiceFaultF" +
            "ault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADUser[]> GetUserInfoByNetworkIdAsync(string networkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoExtendedByNetworkId", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoExtendedByNetworkIdRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoExtendedByNetworkIdADServi" +
            "ceFaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADUserExtended[]> GetUserInfoExtendedByNetworkIdAsync(string networkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoExtendedByNetworkIdStartsW" +
            "ith", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoExtendedByNetworkIdStartsW" +
            "ithResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoExtendedByNetworkIdStartsW" +
            "ithADServiceFaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADUserExtended[]> GetUserInfoExtendedByNetworkIdStartsWithAsync(string networkId, string numResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserAttributeByPpgId", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserAttributeByPpgIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserAttributeByPpgIdADServiceFault" +
            "Fault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<string> GetUserAttributeByPpgIdAsync(string ppgId, string attribute);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserAttributeByNetworkId", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserAttributeByNetworkIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserAttributeByNetworkIdADServiceF" +
            "aultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<string> GetUserAttributeByNetworkIdAsync(string networkId, string attribute);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoByLastNameStartsWith", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoByLastNameStartsWithRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoByLastNameStartsWithADServ" +
            "iceFaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADUser[]> GetUserInfoByLastNameStartsWithAsync(string lastName, string numResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoExtendedByLastNameStartsWi" +
            "th", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoExtendedByLastNameStartsWi" +
            "thResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoExtendedByLastNameStartsWi" +
            "thADServiceFaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADUserExtended[]> GetUserInfoExtendedByLastNameStartsWithAsync(string lastName, string numResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoByNameContains", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoByNameContainsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoByNameContainsADServiceFau" +
            "ltFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADUser[]> GetUserInfoByNameContainsAsync(string partialName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoByDistinguishedNameContain" +
            "s", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoByDistinguishedNameContain" +
            "sResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserInfoByDistinguishedNameContain" +
            "sADServiceFaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADUser[]> GetUserInfoByDistinguishedNameContainsAsync(string distinguishedName, string numResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUsersInGroup", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUsersInGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUsersInGroupADServiceFaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADUser[]> GetUsersInGroupAsync(string groupName, string flatten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUsersInGroupPaged", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUsersInGroupPagedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUsersInGroupPagedADServiceFaultFau" +
            "lt", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADUser[]> GetUsersInGroupPagedAsync(string groupName, string pageSize, string pageNumber, string flatten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserGroupsByPpgId", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserGroupsByPpgIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserGroupsByPpgIdADServiceFaultFau" +
            "lt", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetUserGroupsByPpgIdAsync(string ppgId, string includeDistLists);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserGroupsByNetworkId", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserGroupsByNetworkIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserGroupsByNetworkIdADServiceFaul" +
            "tFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetUserGroupsByNetworkIdAsync(string networkId, string includeDistLists);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserAuthorizationGroupsByUserNameA" +
            "D", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserAuthorizationGroupsByUserNameA" +
            "DResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserAuthorizationGroupsByUserNameA" +
            "DADServiceFaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetUserAuthorizationGroupsByUserNameADAsync(string domain, string networkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserDistributionListsByPpgId", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserDistributionListsByPpgIdRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserDistributionListsByPpgIdADServ" +
            "iceFaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetUserDistributionListsByPpgIdAsync(string ppgId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserDistributionListsByNetworkId", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetUserDistributionListsByNetworkIdRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetUserDistributionListsByNetworkIdAD" +
            "ServiceFaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetUserDistributionListsByNetworkIdAsync(string networkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/IsUserInGroupByPpgId", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/IsUserInGroupByPpgIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/IsUserInGroupByPpgIdADServiceFaultFau" +
            "lt", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<bool> IsUserInGroupByPpgIdAsync(string ppgId, string groupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/IsUserInGroupByNetworkId", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/IsUserInGroupByNetworkIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/IsUserInGroupByNetworkIdADServiceFaul" +
            "tFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<bool> IsUserInGroupByNetworkIdAsync(string networkId, string groupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetGroupInfoByName", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetGroupInfoByNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetGroupInfoByNameADServiceFaultFault" +
            "", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetGroupInfoByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetGroupInfoByNameContains", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetGroupInfoByNameContainsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetGroupInfoByNameContainsADServiceFa" +
            "ultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetGroupInfoByNameContainsAsync(string partialName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetGroupInfoByNameStartsWith", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetGroupInfoByNameStartsWithResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetGroupInfoByNameStartsWithADService" +
            "FaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetGroupInfoByNameStartsWithAsync(string name, string numResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ppg.com/adservice/V1_0/ADService/GetGroupInfoByDistinguishedNameContai" +
            "ns", ReplyAction="http://www.ppg.com/adservice/V1_0/ADService/GetGroupInfoByDistinguishedNameContai" +
            "nsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ADServiceRef.ADServiceFault), Action="http://www.ppg.com/adservice/V1_0/ADService/GetGroupInfoByDistinguishedNameContai" +
            "nsADServiceFaultFault", Name="ADServiceFault", Namespace="http://schemas.ppg.com/adservice/V1_0")]
        System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetGroupInfoByDistinguishedNameContainsAsync(string distinguishedName, string numResults);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface ADServiceChannel : ADServiceRef.ADService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class ADServiceClient : System.ServiceModel.ClientBase<ADServiceRef.ADService>, ADServiceRef.ADService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ADServiceClient() : 
                base(ADServiceClient.GetDefaultBinding(), ADServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ADService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ADServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ADServiceClient.GetBindingForEndpoint(endpointConfiguration), ADServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ADServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ADServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ADServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ADServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ADServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<object> GetUserInfoTestAsync()
        {
            return base.Channel.GetUserInfoTestAsync();
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADUser[]> ADServiceAutoCompleteLastNameAsync(string text, string count)
        {
            return base.Channel.ADServiceAutoCompleteLastNameAsync(text, count);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADUserExtended[]> ADServiceAutoCompleteLastNameExtendedAsync(string text, string count)
        {
            return base.Channel.ADServiceAutoCompleteLastNameExtendedAsync(text, count);
        }
        
        public System.Threading.Tasks.Task<int> GetGroupCountAsync()
        {
            return base.Channel.GetGroupCountAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetUserCountAsync()
        {
            return base.Channel.GetUserCountAsync();
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADUser[]> GetUserInfoByPpgIdAsync(string ppgId)
        {
            return base.Channel.GetUserInfoByPpgIdAsync(ppgId);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADUserExtended[]> GetUserInfoExtendedByPpgIdAsync(string ppgId)
        {
            return base.Channel.GetUserInfoExtendedByPpgIdAsync(ppgId);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADUser[]> GetUserInfoByNetworkIdAsync(string networkId)
        {
            return base.Channel.GetUserInfoByNetworkIdAsync(networkId);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADUserExtended[]> GetUserInfoExtendedByNetworkIdAsync(string networkId)
        {
            return base.Channel.GetUserInfoExtendedByNetworkIdAsync(networkId);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADUserExtended[]> GetUserInfoExtendedByNetworkIdStartsWithAsync(string networkId, string numResults)
        {
            return base.Channel.GetUserInfoExtendedByNetworkIdStartsWithAsync(networkId, numResults);
        }
        
        public System.Threading.Tasks.Task<string> GetUserAttributeByPpgIdAsync(string ppgId, string attribute)
        {
            return base.Channel.GetUserAttributeByPpgIdAsync(ppgId, attribute);
        }
        
        public System.Threading.Tasks.Task<string> GetUserAttributeByNetworkIdAsync(string networkId, string attribute)
        {
            return base.Channel.GetUserAttributeByNetworkIdAsync(networkId, attribute);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADUser[]> GetUserInfoByLastNameStartsWithAsync(string lastName, string numResults)
        {
            return base.Channel.GetUserInfoByLastNameStartsWithAsync(lastName, numResults);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADUserExtended[]> GetUserInfoExtendedByLastNameStartsWithAsync(string lastName, string numResults)
        {
            return base.Channel.GetUserInfoExtendedByLastNameStartsWithAsync(lastName, numResults);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADUser[]> GetUserInfoByNameContainsAsync(string partialName)
        {
            return base.Channel.GetUserInfoByNameContainsAsync(partialName);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADUser[]> GetUserInfoByDistinguishedNameContainsAsync(string distinguishedName, string numResults)
        {
            return base.Channel.GetUserInfoByDistinguishedNameContainsAsync(distinguishedName, numResults);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADUser[]> GetUsersInGroupAsync(string groupName, string flatten)
        {
            return base.Channel.GetUsersInGroupAsync(groupName, flatten);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADUser[]> GetUsersInGroupPagedAsync(string groupName, string pageSize, string pageNumber, string flatten)
        {
            return base.Channel.GetUsersInGroupPagedAsync(groupName, pageSize, pageNumber, flatten);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetUserGroupsByPpgIdAsync(string ppgId, string includeDistLists)
        {
            return base.Channel.GetUserGroupsByPpgIdAsync(ppgId, includeDistLists);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetUserGroupsByNetworkIdAsync(string networkId, string includeDistLists)
        {
            return base.Channel.GetUserGroupsByNetworkIdAsync(networkId, includeDistLists);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetUserAuthorizationGroupsByUserNameADAsync(string domain, string networkId)
        {
            return base.Channel.GetUserAuthorizationGroupsByUserNameADAsync(domain, networkId);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetUserDistributionListsByPpgIdAsync(string ppgId)
        {
            return base.Channel.GetUserDistributionListsByPpgIdAsync(ppgId);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetUserDistributionListsByNetworkIdAsync(string networkId)
        {
            return base.Channel.GetUserDistributionListsByNetworkIdAsync(networkId);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserInGroupByPpgIdAsync(string ppgId, string groupName)
        {
            return base.Channel.IsUserInGroupByPpgIdAsync(ppgId, groupName);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserInGroupByNetworkIdAsync(string networkId, string groupName)
        {
            return base.Channel.IsUserInGroupByNetworkIdAsync(networkId, groupName);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetGroupInfoByNameAsync(string name)
        {
            return base.Channel.GetGroupInfoByNameAsync(name);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetGroupInfoByNameContainsAsync(string partialName)
        {
            return base.Channel.GetGroupInfoByNameContainsAsync(partialName);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetGroupInfoByNameStartsWithAsync(string name, string numResults)
        {
            return base.Channel.GetGroupInfoByNameStartsWithAsync(name, numResults);
        }
        
        public System.Threading.Tasks.Task<ADServiceRef.ADGroup[]> GetGroupInfoByDistinguishedNameContainsAsync(string distinguishedName, string numResults)
        {
            return base.Channel.GetGroupInfoByDistinguishedNameContainsAsync(distinguishedName, numResults);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ADService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ADService))
            {
                return new System.ServiceModel.EndpointAddress("http://ppg.web.ppg.com/ADService/ADService.svc/ADServiceSoap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ADServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ADService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ADServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ADService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ADService,
        }
    }
}
