//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleCOEWorkTracking.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OracleCOEWorkTracking.Resources.UserMessageResource", typeof(UserMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find {0} {1} in database..
        /// </summary>
        internal static string CannotFindFieldInDatabase {
            get {
                return ResourceManager.GetString("CannotFindFieldInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Adding {0}: .
        /// </summary>
        internal static string ErrorAddingField {
            get {
                return ResourceManager.GetString("ErrorAddingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Copying {0}: .
        /// </summary>
        internal static string ErrorCopyingField {
            get {
                return ResourceManager.GetString("ErrorCopyingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Removing {0}: .
        /// </summary>
        internal static string ErrorRemovingField {
            get {
                return ResourceManager.GetString("ErrorRemovingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving {0}: .
        /// </summary>
        internal static string ErrorSavingField {
            get {
                return ResourceManager.GetString("ErrorSavingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving {0}. Field(s) {1} are missing or invalid. .
        /// </summary>
        internal static string ErrorSavingInputInvalid {
            get {
                return ResourceManager.GetString("ErrorSavingInputInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added successfully..
        /// </summary>
        internal static string FieldAddedSuccessfully {
            get {
                return ResourceManager.GetString("FieldAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} already exists in the database..
        /// </summary>
        internal static string FieldAlreadyExists {
            get {
                return ResourceManager.GetString("FieldAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} copied successfully..
        /// </summary>
        internal static string FieldCopiedSuccessfully {
            get {
                return ResourceManager.GetString("FieldCopiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist in the database..
        /// </summary>
        internal static string FieldDoesNotExist {
            get {
                return ResourceManager.GetString("FieldDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty..
        /// </summary>
        internal static string FieldNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("FieldNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} removed successfully..
        /// </summary>
        internal static string FieldRemovedSuccessfully {
            get {
                return ResourceManager.GetString("FieldRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} saved successfully..
        /// </summary>
        internal static string FieldSavedSuccessfully {
            get {
                return ResourceManager.GetString("FieldSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting {0} {1}..
        /// </summary>
        internal static string GetError {
            get {
                return ResourceManager.GetString("GetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting {0}..
        /// </summary>
        internal static string GetListError {
            get {
                return ResourceManager.GetString("GetListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully got {0}..
        /// </summary>
        internal static string GetListSuccess {
            get {
                return ResourceManager.GetString("GetListSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully got {0} {1}..
        /// </summary>
        internal static string GetSuccess {
            get {
                return ResourceManager.GetString("GetSuccess", resourceCulture);
            }
        }
    }
}
